{% set version = "2.15.0" %}

package:
  name: robotframework-pabot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-pabot/robotframework-pabot-{{ version }}.tar.gz
  sha256: 5c648bee01aa4576d2e8cd1c6d34edcc8a976b195bfd49060824b69ea971ab1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - pabot=pabot.pabot:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - natsort >=8.2.0
    - python >=3.6
    - robotframework >=3.2
    - robotframework-stacktrace >=0.4.1

test:
  imports:
    - pabot
    - pabot.py3
  commands:
    - python -m pip check
    - pabot --version
    - pabot --help
  requires:
    - pip

about:
  home: https://pabot.org
  summary: Parallel test runner for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |-
    A parallel executor for Robot Framework tests. With Pabot you can split one 
    execution into multiple and save test execution time.

extra:
  recipe-maintainers:
    - bollwyvl
